services:
  - type: web
    name: amenta-website
    runtime: node
    rootDir: app
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: APP_ID
        sync: false
      - key: APP_SECRET
        sync: false
      - key: KIMI_AUTH_URL
        sync: false
      - key: KIMI_OPEN_URL
        sync: false
      - key: OWNER_UNION_ID
        sync: false
      - key: VITE_APP_ID
        sync: false
      - key: VITE_KIMI_AUTH_URL
        sync: false
